# If something failed the rubocop build and you disagree, disable it here and
# leave a note.

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5.1

  Exclude:
    - 'bin/*'
    - 'Gemfile'
    - 'spec/*'

Rails:
  Enabled: true

# only allow "safe" assignment in conditions
Lint/AssignmentInCondition:
  AllowSafeAssignment: true

# standard cucumber step definitions cause lint errors, safe to ignore.
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'features/step_definitions/**/*.rb'

# Ignore warnings about code complexity
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Layout/AccessModifierIndentation:
  Enabled: false
Style/AccessorMethodName:
  Enabled: false
Layout/AlignArray:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Layout/AlignParameters:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/BarePercentLiterals:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Layout/BlockEndNewline:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Layout/CaseIndentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassVars:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: false
Style/ColonMethodCall:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/DotPosition:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundMethodBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/IndentFirstArgument:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Layout/IndentFirstArrayElement:
  Enabled: false
Layout/IndentFirstHashElement:
  Enabled: false
Layout/IndentationConsistency:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Style/Lambda:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/MultilineMethodCallIndentation:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/Not:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/ParenthesesAroundCondition:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/PercentQLiterals:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/PredicateName:
  Enabled: false
Style/Proc:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Layout/SpaceAfterComma:
  Enabled: false
Layout/SpaceBeforeComma:
  Enabled: false
Style/SignalException:
  Enabled: false
Layout/SpaceInsideStringInterpolation:
  Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Layout/SpaceAroundBlockParameters:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceInsideBrackets:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideParens:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Layout/TrailingBlankLines:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/UnlessElse:
  Enabled: false
Style/UnneededPercentQ:
  Enabled: false
Style/WordArray:
  Enabled: false
Layout/SpaceBeforeFirstArg:
  Enabled: false
Layout/SpaceAroundKeyword:
  Enabled: false
Lint/EmptyWhen:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Rails/HttpPositionalArguments:
  Enabled: false
Rails/Blank:
  Enabled: false
Layout/IndentHeredoc:
  Enabled: false
Style/NumericPredicate:
  Enabled: false

Rails/OutputSafety:
  Exclude:

Rails/DynamicFindBy:
  Enabled: false