language: ruby
services:
  - postgresql
cache:
- bundler
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake assets:precompile
script:
  - rspec
  - rubocop
deploy:
  provider: heroku
  api_key:
    secure: L508tAapSdNQKkxjiUO9luYVhsEVt8oB2jigVzgkn4m6Qr0xhfHw9eqMpwJcahDjeDAeM3keD+L1z6/rtBpsSHuS0a6tWAjnBsSJSVGii3y/mCMYbFikKRkoExtGIP4e5GppWiljrEvwC8G8/6syb4diGaWA4Av3ViaOFqXLbW3EkGEJmRFkuwZtZetBc+tchgh31KqQ5OARFe9yY9PPOWszIg6d/Neo2ZoV5yFBTYunCbmiBrMJaJMAYZ3F1XCv/PoZA5N/t1PPf4Il2KtBaA1J8zjUFSMVH9obP4CsYX1N/sGSjUH0H2uHizK5nbx4PcDr7EaLXOvwZANGLo/FpAoN52SA8itpHDzdE2Z9UHpkOZs8mmAdEP9dYOSq19ThLhBsGaTSXGUkZb50yS39a+aI5ICLDQnW+WT+e/tMPUPAB9zHkR8e+x3Dj/WKK+916h54RHHv9Rkm5zWRxK/m3RUrHMkyCqzzW54wyzEU3jkdCxTdFdNyUNDjOMXyr1Q5Vpy3VBEBkicCz7eer/tSwFSQWuiQ2HwxvDYenE5N/jGIuGaEn+SqZw82b+ltPytE4H7jqRwB1Ch4BYJrm6Q6ZiPoV7pVFdThg/CzeIxwPkquAYWaZ3zsWF2+hucZUmZjXAALx0MHbrGWphxIBwpfYB3dTJwFawbV27pyRymolrI=
  app: btf-app
  on:
    repo: chrisjgilbert/btf-app
